"""initial schema

Revision ID: 6df4e6043dc1
Revises: 
Create Date: 2026-09-08 10:28:05.540514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '6df4e6043dc1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fix_examples',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('error_description', sa.Text(), nullable=False),
    sa.Column('fix_diff', sa.Text(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('service', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('raw', sa.Text(), nullable=False),
    sa.Column('correlation_id', sa.String(), nullable=True),
    sa.Column('commit_hash', sa.String(), nullable=True),
    sa.Column('commit_author', sa.String(), nullable=True),
    sa.Column('commit_summary', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fix_suggestions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('log_event_id', sa.UUID(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('diff', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['log_event_id'], ['log_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fix_suggestions')
    op.drop_table('log_events')
    op.drop_table('fix_examples')
    # ### end Alembic commands ###
