"""issue grouping, ingestion auth, github, webhooks, team sharing

Revision ID: 82f556f4e248
Revises: ae6a34e2688f
Create Date: 2026-09-08 18:54:47.682596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82f556f4e248'
down_revision: Union[str, None] = 'ae6a34e2688f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Local dev/demo data only (no production deployment exists yet — see
    # DECISIONS.md). fix_suggestions/log_events/log_sources rows created
    # under the old per-event schema have no meaningful issue_id or
    # api_key_hash to backfill, so this wipes them rather than fabricating
    # placeholder values; a real migration against live data would instead
    # backfill Issue rows from the existing log_events. Wiping is logged
    # here explicitly as the shortcut it is, per CLAUDE.md's working
    # agreement on deviating from the ideal path.
    op.execute("DELETE FROM fix_suggestions")
    op.execute("DELETE FROM log_events")
    op.execute("DELETE FROM log_sources")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('invited_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('issues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('log_source_id', sa.UUID(), nullable=False),
    sa.Column('fingerprint', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('service', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('commit_hash', sa.String(), nullable=True),
    sa.Column('commit_author', sa.String(), nullable=True),
    sa.Column('commit_summary', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['log_source_id'], ['log_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issues_fingerprint'), 'issues', ['fingerprint'], unique=False)
    op.add_column('fix_suggestions', sa.Column('issue_id', sa.UUID(), nullable=False))
    op.add_column('fix_suggestions', sa.Column('added_to_knowledge_base', sa.Boolean(), nullable=False))
    op.drop_constraint('fix_suggestions_log_event_id_fkey', 'fix_suggestions', type_='foreignkey')
    op.create_foreign_key(None, 'fix_suggestions', 'issues', ['issue_id'], ['id'])
    op.drop_column('fix_suggestions', 'log_event_id')
    op.add_column('log_events', sa.Column('issue_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'log_events', 'issues', ['issue_id'], ['id'])
    op.add_column('log_sources', sa.Column('api_key_hash', sa.String(), nullable=False))
    op.create_index(op.f('ix_log_sources_api_key_hash'), 'log_sources', ['api_key_hash'], unique=True)
    op.add_column('projects', sa.Column('webhook_url', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('github_repo', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('github_token_encrypted', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'github_token_encrypted')
    op.drop_column('projects', 'github_repo')
    op.drop_column('projects', 'webhook_url')
    op.drop_index(op.f('ix_log_sources_api_key_hash'), table_name='log_sources')
    op.drop_column('log_sources', 'api_key_hash')
    op.drop_constraint(None, 'log_events', type_='foreignkey')
    op.drop_column('log_events', 'issue_id')
    op.add_column('fix_suggestions', sa.Column('log_event_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'fix_suggestions', type_='foreignkey')
    op.create_foreign_key('fix_suggestions_log_event_id_fkey', 'fix_suggestions', 'log_events', ['log_event_id'], ['id'])
    op.drop_column('fix_suggestions', 'added_to_knowledge_base')
    op.drop_column('fix_suggestions', 'issue_id')
    op.drop_index(op.f('ix_issues_fingerprint'), table_name='issues')
    op.drop_table('issues')
    op.drop_table('project_members')
    # ### end Alembic commands ###
